apiVersion: v1
kind: Template
metadata:
  name: graph-sync-operator-deployment
  annotations:
    description: This is Thoth - Graph Sync Operator
    openshift.io/display-name: 'Thoth Core: Graph Sync Operator'
    version: 0.0.1
    tags: poc,thoth,graph-sync-operator,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Graph Sync
      Operator on OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: graph-sync-operator-deployment
    app: thoth
    component: graph-sync-operator

objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: thoth
        component: graph-sync-operator
      name: "graph-sync-operator-${THOTH_OPERATOR_NAMESPACE}"
    spec:
      replicas: 1
      selector:
        name: graph-sync-operator
      template:
        metadata:
          labels:
            app: thoth
            name: graph-sync-operator
        spec:
          serviceAccountName: "${THOTH_SERVICE_ACCOUNT_NAME}"
          containers:
            - name: graph-sync-operator
              env:
                - name: KUBERNETES_API_URL
                  value: 'https://kubernetes.default.svc.cluster.local'		
                - name: KUBERNETES_VERIFY_TLS		
                  value: "0"		
                - name: THOTH_FRONTEND_NAMESPACE		
                  valueFrom:		
                    configMapKeyRef:		
                      key: frontend-namespace		
                      name: thoth
                - name: THOTH_MIDDLETIER_NAMESPACE	
                  valueFrom:	
                    configMapKeyRef:	
                      key: middletier-namespace	
                      name: thoth
                - name: THOTH_BACKEND_NAMESPACE	
                  valueFrom:	
                    configMapKeyRef:	
                      key: backend-namespace	
                      name: thoth
                - name: THOTH_OPERATOR_NAMESPACE
                  value: ${THOTH_OPERATOR_NAMESPACE}
                - name: THOTH_GRAPH_SYNC_NAMESPACE
                  value: ${THOTH_GRAPH_SYNC_NAMESPACE}
                - name: THOTH_LOG_GRAPH_SYNC_OPERATOR
                  value: INFO
                - name: THOTH_INFRA_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: infra-namespace
                      name: thoth
                - name: PROMETHEUS_PUSHGATEWAY_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: prometheus-pushgateway-host
                      name: thoth
                - name: PROMETHEUS_PUSHGATEWAY_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: prometheus-pushgateway-port
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
              resources:
                requests:
                  memory: "384Mi"
                  cpu: "250m"
                limits:
                  memory: "384Mi"
                  cpu: "250m"
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - graph-sync-operator
            from:
              kind: ImageStreamTag
              name: 'graph-sync-operator:${IMAGE_STREAM_TAG}'

parameters:
  - description: Tag of the ImageStream to use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

  - description: Name of the service account which allows operator schedule graph syncs in operated namespace.
    displayName: Service account name
    required: true
    name: THOTH_SERVICE_ACCOUNT_NAME

  - name: THOTH_OPERATOR_NAMESPACE
    description: Namespace in which operator is handling events.
    displayName: Operator namespace
    required: true

  - name: THOTH_GRAPH_SYNC_NAMESPACE
    description: Namespace in which graph syncs should be run.
    displayName: Graph sync namespace
    required: true
